// Copyright 2025 Roman Plotnikov. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glslens_GLSLens */

#ifndef _Included_com_glslens_GLSLens
#define _Included_com_glslens_GLSLens
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glslens_GLSLens
 * Method:    getLiveUniformsInfo
 * Signature: (Ljava/lang/String;II)[Lcom/glslens/UniformInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_glslens_GLSLens_getLiveUniformsInfo
        (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_glslens_GLSLens
 * Method:    initializeProcess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glslens_GLSLens_initializeProcess
(JNIEnv *, jobject);

/*
 * Class:     com_glslens_GLSLens
 * Method:    finalizeProcess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glslens_GLSLens_finalizeProcess
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
